<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-A33NF1HV" ignored="0" name="Retryfailedtest" tests="4" failures="1" timestamp="2021-04-11T19:47:01 IST" time="0.06" errors="0">
  <testcase name="Test1" time="0.013" classname="analyzer.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="analyzer.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="analyzer.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="analyzer.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at analyzer.MyTest.Test1(MyTest.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Retryfailedtest -->
